export const EXERCISE_LIST = [
    '1-Arm 45 Cable Rear Delt Flye',
    '45° Hyperextension',
    '45° Incline Barbell Press',
    '45° Incline DB Press',
    '45° Incline Machine Press',
    'Ab Wheel Rollout',
    'Arm Circles',
    'Arm Swings',
    'Arm-Out Single Arm DB Row',
    'Barbell Bench Press',
    'Barbell RDL',
    'Bayesian Cable Curl',
    'Bench Dip',
    'Bottom-Half DB Flye',
    'Bottom-Half Seated Cable Flye',
    'Cable Crossover Ladder',
    'Cable Crunch',
    'Cable External Rotation',
    'Cable Hip Abduction',
    'Cable Hip Adduction',
    'Cable Paused Shrug-In',
    'Cable Pull-Through',
    'Cable Rope Hammer Curl',
    'Cable Shoulder Press',
    'Cable Triceps Kickback',
    'Chest-Supported Machine Row',
    'Chest-Supported T-Bar Row',
    'Concentration Cable Curl',
    'Copenhagen Hip Adduction',
    'DB Bulgarian Split Squat',
    'DB Concentration Curl',
    'DB Curl',
    'DB Hammer Curl',
    'DB Preacher Curl',
    'DB RDL',
    'DB Shoulder Press',
    'DB Shrug',
    'DB Skull Crusher',
    'DB Static Lunge',
    'DB Step-Up',
    'DB Triceps Kickback',
    'DB Walking Lunge',
    'Decline Weighted Crunch',
    'Dual-Handle Elbows-Out Cable Row',
    'Dual-Handle Lat Pulldown',
    'EZ-Bar Cable Curl',
    'EZ-Bar Curl',
    'EZ-Bar Preacher Curl',
    'EZ-Bar Skull Crusher',
    'Front-to-Back Leg Swings',
    'Glute-Ham Raise',
    'Goblet Squat',
    'Hack Squat',
    'Hammer Preacher Curl',
    'Hanging Leg Raise',
    'Helms Row',
    'High-Bar Back Squat',
    'High-Cable Cuffed Lateral Raise',
    'High-Cable Lateral Raise',
    'Incline Chest-Supported DB Row',
    'Incline DB Stretch Curl',
    'Katana Triceps Extension',
    'Lateral Band Walk',
    'Lean-Back Lat Pulldown',
    'Lean-Back Machine Pulldown',
    'Lean-In DB Lateral Raise',
    'Leg Extension',
    'Leg Press',
    'Leg Press Calf Press',
    'Long-Lever Plank',
    'Low-to-High Cable Crossover',
    'Lunge',
    'Lying Leg Curl',
    'Machine Chest Press',
    'Machine Crunch',
    'Machine Hip Abduction',
    'Machine Hip Adduction',
    'Machine Preacher Curl',
    'Machine Shoulder Press',
    'Machine Shrug',
    'Meadows Row',
    'Modified Candlestick',
    'Neutral-Grip Lat Pulldown',
    'Neutral-Grip Pull-Up',
    'Neutral-Grip Seated Cable Row',
    'Nordic Ham Curl',
    'Overhead Cable Triceps Extension (Bar)',
    'Overhead Cable Triceps Extension (Rope)',
    'Pec Deck',
    'Pendlay Deficit Row',
    'Pull-Up',
    'Reverse Nordic',
    'Reverse Pec Deck',
    'Roman Chair Leg Raise',
    'Rope Face Pull',
    'Seated Calf Raise',
    'Seated DB Shoulder Press',
    'Seated Leg Curl',
    'Seated Super-Bayesian High Cable Curl',
    'Side-to-Side Leg Swings',
    'Single-Arm DB Row',
    'Sissy Squat',
    'Smith Machine Row',
    'Smith Machine Squat',
    'Smith Machine Static Lunge',
    'Smith Machine Static Lunge w/ Elevated Front Foot',
    'Snatch-Grip RDL',
    'Standing Calf Raise',
    'Swiss Ball Rollout',
    'Triceps Pressdown (Bar)',
    'Triceps Pressdown (Rope)',
    'Walking Lunge',
    'Wide-Grip Lat Pulldown',
    'Wide-Grip Pull-Up'
].sort();

export interface ExerciseMetadata {
    muscle: string;
}

export const EXERCISE_METADATA: Record<string, ExerciseMetadata> = {
    '1-Arm 45 Cable Rear Delt Flye': { muscle: 'Shoulders' },
    '45° Hyperextension': { muscle: 'Back' },
    '45° Incline Barbell Press': { muscle: 'Chest' },
    '45° Incline DB Press': { muscle: 'Chest' },
    '45° Incline Machine Press': { muscle: 'Chest' },
    'Ab Wheel Rollout': { muscle: 'Core' },
    'Arm Circles': { muscle: 'Shoulders' },
    'Arm Swings': { muscle: 'Shoulders' },
    'Arm-Out Single Arm DB Row': { muscle: 'Back' },
    'Barbell Bench Press': { muscle: 'Chest' },
    'Barbell RDL': { muscle: 'Legs' },
    'Bayesian Cable Curl': { muscle: 'Arms' },
    'Bench Dip': { muscle: 'Arms' },
    'Bottom-Half DB Flye': { muscle: 'Chest' },
    'Bottom-Half Seated Cable Flye': { muscle: 'Chest' },
    'Cable Crossover Ladder': { muscle: 'Chest' },
    'Cable Crunch': { muscle: 'Core' },
    'Cable External Rotation': { muscle: 'Shoulders' },
    'Cable Hip Abduction': { muscle: 'Legs' },
    'Cable Hip Adduction': { muscle: 'Legs' },
    'Cable Paused Shrug-In': { muscle: 'Back' },
    'Cable Pull-Through': { muscle: 'Legs' },
    'Cable Rope Hammer Curl': { muscle: 'Arms' },
    'Cable Shoulder Press': { muscle: 'Shoulders' },
    'Cable Triceps Kickback': { muscle: 'Arms' },
    'Chest-Supported Machine Row': { muscle: 'Back' },
    'Chest-Supported T-Bar Row': { muscle: 'Back' },
    'Concentration Cable Curl': { muscle: 'Arms' },
    'Copenhagen Hip Adduction': { muscle: 'Legs' },
    'DB Bulgarian Split Squat': { muscle: 'Legs' },
    'DB Concentration Curl': { muscle: 'Arms' },
    'DB Curl': { muscle: 'Arms' },
    'DB Hammer Curl': { muscle: 'Arms' },
    'DB Preacher Curl': { muscle: 'Arms' },
    'DB RDL': { muscle: 'Legs' },
    'DB Shoulder Press': { muscle: 'Shoulders' },
    'DB Shrug': { muscle: 'Back' },
    'DB Skull Crusher': { muscle: 'Arms' },
    'DB Static Lunge': { muscle: 'Legs' },
    'DB Step-Up': { muscle: 'Legs' },
    'DB Triceps Kickback': { muscle: 'Arms' },
    'DB Walking Lunge': { muscle: 'Legs' },
    'Decline Weighted Crunch': { muscle: 'Core' },
    'Dual-Handle Elbows-Out Cable Row': { muscle: 'Back' },
    'Dual-Handle Lat Pulldown': { muscle: 'Back' },
    'EZ-Bar Cable Curl': { muscle: 'Arms' },
    'EZ-Bar Curl': { muscle: 'Arms' },
    'EZ-Bar Preacher Curl': { muscle: 'Arms' },
    'EZ-Bar Skull Crusher': { muscle: 'Arms' },
    'Front-to-Back Leg Swings': { muscle: 'Legs' },
    'Glute-Ham Raise': { muscle: 'Legs' },
    'Goblet Squat': { muscle: 'Legs' },
    'Hack Squat': { muscle: 'Legs' },
    'Hammer Preacher Curl': { muscle: 'Arms' },
    'Hanging Leg Raise': { muscle: 'Core' },
    'Helms Row': { muscle: 'Back' },
    'High-Bar Back Squat': { muscle: 'Legs' },
    'High-Cable Cuffed Lateral Raise': { muscle: 'Shoulders' },
    'High-Cable Lateral Raise': { muscle: 'Shoulders' },
    'Incline Chest-Supported DB Row': { muscle: 'Back' },
    'Incline DB Stretch Curl': { muscle: 'Arms' },
    'Katana Triceps Extension': { muscle: 'Arms' },
    'Lateral Band Walk': { muscle: 'Legs' },
    'Lean-Back Lat Pulldown': { muscle: 'Back' },
    'Lean-Back Machine Pulldown': { muscle: 'Back' },
    'Lean-In DB Lateral Raise': { muscle: 'Shoulders' },
    'Leg Extension': { muscle: 'Legs' },
    'Leg Press': { muscle: 'Legs' },
    'Leg Press Calf Press': { muscle: 'Legs' },
    'Long-Lever Plank': { muscle: 'Core' },
    'Low-to-High Cable Crossover': { muscle: 'Chest' },
    'Lunge': { muscle: 'Legs' },
    'Lying Leg Curl': { muscle: 'Legs' },
    'Machine Chest Press': { muscle: 'Chest' },
    'Machine Crunch': { muscle: 'Core' },
    'Machine Hip Abduction': { muscle: 'Legs' },
    'Machine Hip Adduction': { muscle: 'Legs' },
    'Machine Preacher Curl': { muscle: 'Arms' },
    'Machine Shoulder Press': { muscle: 'Shoulders' },
    'Machine Shrug': { muscle: 'Back' },
    'Meadows Row': { muscle: 'Back' },
    'Modified Candlestick': { muscle: 'Core' },
    'Neutral-Grip Lat Pulldown': { muscle: 'Back' },
    'Neutral-Grip Pull-Up': { muscle: 'Back' },
    'Neutral-Grip Seated Cable Row': { muscle: 'Back' },
    'Nordic Ham Curl': { muscle: 'Legs' },
    'Overhead Cable Triceps Extension (Bar)': { muscle: 'Arms' },
    'Overhead Cable Triceps Extension (Rope)': { muscle: 'Arms' },
    'Pec Deck': { muscle: 'Chest' },
    'Pendlay Deficit Row': { muscle: 'Back' },
    'Pull-Up': { muscle: 'Back' },
    'Reverse Nordic': { muscle: 'Legs' },
    'Reverse Pec Deck': { muscle: 'Shoulders' },
    'Roman Chair Leg Raise': { muscle: 'Core' },
    'Rope Face Pull': { muscle: 'Shoulders' },
    'Seated Calf Raise': { muscle: 'Legs' },
    'Seated DB Shoulder Press': { muscle: 'Shoulders' },
    'Seated Leg Curl': { muscle: 'Legs' },
    'Seated Super-Bayesian High Cable Curl': { muscle: 'Arms' },
    'Side-to-Side Leg Swings': { muscle: 'Legs' },
    'Single-Arm DB Row': { muscle: 'Back' },
    'Sissy Squat': { muscle: 'Legs' },
    'Smith Machine Row': { muscle: 'Back' },
    'Smith Machine Squat': { muscle: 'Legs' },
    'Smith Machine Static Lunge': { muscle: 'Legs' },
    'Smith Machine Static Lunge w/ Elevated Front Foot': { muscle: 'Legs' },
    'Snatch-Grip RDL': { muscle: 'Legs' },
    'Standing Calf Raise': { muscle: 'Legs' },
    'Swiss Ball Rollout': { muscle: 'Core' },
    'Triceps Pressdown (Bar)': { muscle: 'Arms' },
    'Triceps Pressdown (Rope)': { muscle: 'Arms' },
    'Walking Lunge': { muscle: 'Legs' },
    'Wide-Grip Lat Pulldown': { muscle: 'Back' },
    'Wide-Grip Pull-Up': { muscle: 'Back' }
};